# pubspec.yaml
name: baikieamtracuoiky
description: A Flutter Task Manager application with SQLite database support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.5
  path_provider: ^2.1.5
  path: ^1.9.0
  provider: ^6.1.5
  file_picker: ^8.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true